var nameList = [
  'Aarav', 'Vivaan', 'Aditya', 'Vihaan', 'Arjun', 'Sai', 'Reyansh', 'Ayaan',
  'Krishna', 'Ishaan', 'Shaurya', 'Atharv', 'Kartik', 'Dhruv', 'Rudra',
  'Aryan', 'Ansh', 'Kabir', 'Om', 'Yuvraj', 'Rohan', 'Tanish', 'Laksh',
  'Nikhil', 'Manav', 'Harsh', 'Dev', 'Raj', 'Aniket', 'Siddharth', 'Kunal',
  'Samar', 'Abhay', 'Uday', 'Raghav', 'Tarun', 'Virat', 'Ajay', 'Karan',
  'Neeraj', 'Parth', 'Suresh', 'Ramesh', 'Arvind', 'Amit', 'Sanjay', 'Deepak',
  'Mehul', 'Yash', 'Naveen', 'Prem','Liam', 'Noah', 'Oliver', 'Elijah', 'James', 'William', 'Benjamin',
  'Lucas', 'Henry', 'Alexander', 'Mason', 'Michael', 'Ethan', 'Daniel',
  'Jacob', 'Logan', 'Jackson', 'Levi', 'Sebastian', 'Mateo', 'Jack',
  'Owen', 'Theodore', 'Aiden', 'Samuel', 'Joseph', 'John', 'David',
  'Wyatt', 'Matthew', 'Luke', 'Asher', 'Carter', 'Julian', 'Grayson',
  'Leo', 'Jayden', 'Gabriel', 'Isaac', 'Lincoln', 'Anthony', 'Hudson',
  'Dylan', 'Ezra', 'Thomas', 'Charles', 'Christopher', 'Jaxon', 'Maverick',
  'Josiah', 'Isaiah', 'Andrew', 'Elias', 'Joshua', 'Nathan', 'Caleb',
  'Ryan', 'Adrian', 'Miles', 'Eli', 'Nolan', 'Christian', 'Aaron', 'Cameron',
  'Ezekiel', 'Colton', 'Luca', 'Landon', 'Hunter', 'Jonathan', 'Santiago',
  'Axel', 'Easton', 'Cooper', 'Jeremiah', 'Angel', 'Roman', 'Connor',
  'Aanya', 'Ananya', 'Aarohi', 'Ira', 'Diya', 'Saanvi', 'Anika', 'Ishita',
  'Myra', 'Meera', 'Aadhya', 'Navya', 'Kritika', 'Riya', 'Tara', 'Trisha',
  'Shruti', 'Nandini', 'Sneha', 'Radhika', 'Pooja', 'Simran', 'Isha', 'Divya',
  'Neha', 'Priya', 'Kavya', 'Jhanvi', 'Nikita', 'Tanvi', 'Aishwarya', 'Lakshmi',
  'Radha', 'Bhavana', 'Vaishnavi', 'Swati', 'Anushka', 'Mira', 'Payal', 'Rekha',
  'Kalpana', 'Chitra', 'Smita', 'Geeta', 'Kiran', 'Sarita', 'Usha', 'Leela', 'Madhu'
];

export function generateRandomNames() {
  return nameList[Math.floor(Math.random() * nameList.length)];

}

const chatMessages = [
  "This is awesome! 🔥",
  "Who else is watching in 2025?",
  "Lol 😂",
  "Best stream ever!",
  "Can’t stop watching this!",
  "Waiting for the next part!",
  "This made my day 🙌",
  "❤️ from India!",
  "Wow! Incredible content.",
  "Chat going wild 😂",
  "Love this video!",
  "Subscribed instantly!",
  "Haha nice one!",
  "Who's here before 1M views?",
  "Just wow 🔥",
  "Can we get a like spike?",
  "Anyone else here from Mumbai?",
  "Legendary moment 💯",
  "I’ve watched this 10 times already!",
  "Keep it up bro!",
  "Can’t stop laughing 😂",
  "Where’s everyone from? 🌍",
  "This deserves more views!",
  "How is this not viral yet?!",
  "Back again to watch this masterpiece!",
  "He really said THAT 😳",
  "Absolute banger 🔥🔥🔥",
  "This is going in my favorites 💯",
  "Streaming this on loop 🔁",
  "Chat is on fire today! 🔥",
  "Respect to the editor 🙌",
  "Is this real life? 😮",
  "Hands down the best video today!",
  "Those transitions tho 🤌",
  "I’ve watched this 5 times already 😂",
  "Yooo that was smooth 👀",
  "Can someone clip this moment?",
  "How is he so good at this?",
  "I wasn't ready for that ending 😭",
  "BRUH 😭😭😭",
  "This man deserves an award 🏆",
  "Here before it blows up!",
  "Bro just dropped a cinematic masterpiece 🎥",
  "Underrated AF 🔥",
  "No way that just happened 😨",
  "We need a part 2 ASAP!",
  "This guy never disappoints 👏",
  "VIBES. ONLY. 🎧",
  "Who's vibing with this? 🙋‍♂️",
  "Legit got goosebumps 🐓",
  "Time well spent 💯",
  "First time here. Subscribed instantly!",
  "THE GOAT 🐐",
  "Who's still watching in 2025?",
  "This is peak content 📈",
  "I can’t stop rewatching this part!",
  "Tell me I’m not the only one obsessed 😩",
  "Bro just casually dropped heat 🔥",
  "Insanely good 💥",
  "Every second of this is GOLD",
  "I can’t even blink 👁️",
  "W stream, W chat 🙌",
  "Dropped my phone watching this 😂",
  "Actual chills rn ❄️",
  "WHO EDITED THIS?! 🤯",
  "Comment section is wild rn 💬",
  "Give this man his flowers 💐",
  "Replay button getting tired 🔁"
];

export function generateRandomChatMessage() {

  return chatMessages[Math.floor(Math.random() * chatMessages.length)];
 
}